# Generated by Django 4.0.6 on 2026-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0016_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultexpense',
            name='category',
            field=models.IntegerField(choices=[(1, '固定費'), (2, '変動費'), (3, '単発')], default=1, verbose_name='費目区分'),
        ),
        migrations.AddField(
            model_name='defaultexpense',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='必須/任意'),
        ),
    ]
