# Generated by Django 4.0.6 on 2026-06-22 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0017_defaultexpense_category_defaultexpense_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'シミュレーションシナリオ',
                'verbose_name_plural': 'シミュレーションシナリオ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pay_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('amount', models.PositiveIntegerField()),
                ('category', models.IntegerField(choices=[(1, '固定費'), (2, '変動費'), (3, '単発')], default=1, verbose_name='費目区分')),
                ('is_required', models.BooleanField(default=True, verbose_name='必須/任意')),
                ('is_enabled', models.BooleanField(default=True)),
                ('months', models.JSONField(default=list)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.method')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='income_and_expense.scenario')),
            ],
            options={
                'verbose_name': 'シナリオ項目',
                'verbose_name_plural': 'シナリオ項目',
            },
        ),
    ]
